name: Github Action Start
on:
  push:
    branches:
      - master
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Event trigger notification 
        run: echo "Job is automatically triggered by a ${{ github.event_name }}"
      - name: Operating system information 
        run: echo "OS is ${{ runner.os }}"
      - name: Branch and repository name
        run: echo "Branch is ${{ github.ref }} on repository ${{ github.repository }}"
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Name of cloned repository
        run: echo "The repository ${{ github.repository }} has been cloned"
      - name: List files in the repository
        run: ls -l ${{ github.workspace }}
      - name: Show job status
        run: echo "Job status is ${{ job.status }}"
      
